//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class SetModeFeedback : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/SetMode";
        public override string RosMessageName => k_RosMessageName;

        //  feedback
        public sbyte current_robot_mode;
        public sbyte current_safety_mode;

        public SetModeFeedback()
        {
            this.current_robot_mode = 0;
            this.current_safety_mode = 0;
        }

        public SetModeFeedback(sbyte current_robot_mode, sbyte current_safety_mode)
        {
            this.current_robot_mode = current_robot_mode;
            this.current_safety_mode = current_safety_mode;
        }

        public static SetModeFeedback Deserialize(MessageDeserializer deserializer) => new SetModeFeedback(deserializer);

        private SetModeFeedback(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_robot_mode);
            deserializer.Read(out this.current_safety_mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_robot_mode);
            serializer.Write(this.current_safety_mode);
        }

        public override string ToString()
        {
            return "SetModeFeedback: " +
            "\ncurrent_robot_mode: " + current_robot_mode.ToString() +
            "\ncurrent_safety_mode: " + current_safety_mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Feedback);
        }
    }
}
