//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class SetModeResult : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/SetMode";
        public override string RosMessageName => k_RosMessageName;

        //  result
        public bool success;
        public string message;

        public SetModeResult()
        {
            this.success = false;
            this.message = "";
        }

        public SetModeResult(bool success, string message)
        {
            this.success = success;
            this.message = message;
        }

        public static SetModeResult Deserialize(MessageDeserializer deserializer) => new SetModeResult(deserializer);

        private SetModeResult(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.success);
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.success);
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "SetModeResult: " +
            "\nsuccess: " + success.ToString() +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Result);
        }
    }
}
