//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class ProgramStateMsg : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/ProgramState";
        public override string RosMessageName => k_RosMessageName;

        public const string STOPPED = "STOPPED";
        public const string PLAYING = "PLAYING";
        public const string PAUSED = "PAUSED";
        public string state;

        public ProgramStateMsg()
        {
            this.state = "";
        }

        public ProgramStateMsg(string state)
        {
            this.state = state;
        }

        public static ProgramStateMsg Deserialize(MessageDeserializer deserializer) => new ProgramStateMsg(deserializer);

        private ProgramStateMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.state);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
        }

        public override string ToString()
        {
            return "ProgramStateMsg: " +
            "\nstate: " + state.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
