//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class RobotModeMsg : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/RobotMode";
        public override string RosMessageName => k_RosMessageName;

        public const sbyte NO_CONTROLLER = -1;
        public const sbyte DISCONNECTED = 0;
        public const sbyte CONFIRM_SAFETY = 1;
        public const sbyte BOOTING = 2;
        public const sbyte POWER_OFF = 3;
        public const sbyte POWER_ON = 4;
        public const sbyte IDLE = 5;
        public const sbyte BACKDRIVE = 6;
        public const sbyte RUNNING = 7;
        public const sbyte UPDATING_FIRMWARE = 8;
        public sbyte mode;

        public RobotModeMsg()
        {
            this.mode = 0;
        }

        public RobotModeMsg(sbyte mode)
        {
            this.mode = mode;
        }

        public static RobotModeMsg Deserialize(MessageDeserializer deserializer) => new RobotModeMsg(deserializer);

        private RobotModeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "RobotModeMsg: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
