//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class SafetyModeMsg : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/SafetyMode";
        public override string RosMessageName => k_RosMessageName;

        public const byte NORMAL = 1;
        public const byte REDUCED = 2;
        public const byte PROTECTIVE_STOP = 3;
        public const byte RECOVERY = 4;
        public const byte SAFEGUARD_STOP = 5;
        public const byte SYSTEM_EMERGENCY_STOP = 6;
        public const byte ROBOT_EMERGENCY_STOP = 7;
        public const byte VIOLATION = 8;
        public const byte FAULT = 9;
        public const byte VALIDATE_JOINT_ID = 10;
        public const byte UNDEFINED_SAFETY_MODE = 11;
        public const byte AUTOMATIC_MODE_SAFEGUARD_STOP = 12;
        public const byte SYSTEM_THREE_POSITION_ENABLING_STOP = 13;
        public byte mode;

        public SafetyModeMsg()
        {
            this.mode = 0;
        }

        public SafetyModeMsg(byte mode)
        {
            this.mode = mode;
        }

        public static SafetyModeMsg Deserialize(MessageDeserializer deserializer) => new SafetyModeMsg(deserializer);

        private SafetyModeMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.mode);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.mode);
        }

        public override string ToString()
        {
            return "SafetyModeMsg: " +
            "\nmode: " + mode.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
