//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class GetLoadedProgramResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/GetLoadedProgram";
        public override string RosMessageName => k_RosMessageName;

        public string answer;
        public string program_name;
        public bool success;

        public GetLoadedProgramResponse()
        {
            this.answer = "";
            this.program_name = "";
            this.success = false;
        }

        public GetLoadedProgramResponse(string answer, string program_name, bool success)
        {
            this.answer = answer;
            this.program_name = program_name;
            this.success = success;
        }

        public static GetLoadedProgramResponse Deserialize(MessageDeserializer deserializer) => new GetLoadedProgramResponse(deserializer);

        private GetLoadedProgramResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.answer);
            deserializer.Read(out this.program_name);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.answer);
            serializer.Write(this.program_name);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetLoadedProgramResponse: " +
            "\nanswer: " + answer.ToString() +
            "\nprogram_name: " + program_name.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
