//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class GetProgramStateRequest : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/GetProgramState";
        public override string RosMessageName => k_RosMessageName;


        public GetProgramStateRequest()
        {
        }
        public static GetProgramStateRequest Deserialize(MessageDeserializer deserializer) => new GetProgramStateRequest(deserializer);

        private GetProgramStateRequest(MessageDeserializer deserializer)
        {
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
        }

        public override string ToString()
        {
            return "GetProgramStateRequest: ";
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
