//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class GetProgramStateResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/GetProgramState";
        public override string RosMessageName => k_RosMessageName;

        public ProgramStateMsg state;
        public string program_name;
        public string answer;
        public bool success;

        public GetProgramStateResponse()
        {
            this.state = new ProgramStateMsg();
            this.program_name = "";
            this.answer = "";
            this.success = false;
        }

        public GetProgramStateResponse(ProgramStateMsg state, string program_name, string answer, bool success)
        {
            this.state = state;
            this.program_name = program_name;
            this.answer = answer;
            this.success = success;
        }

        public static GetProgramStateResponse Deserialize(MessageDeserializer deserializer) => new GetProgramStateResponse(deserializer);

        private GetProgramStateResponse(MessageDeserializer deserializer)
        {
            this.state = ProgramStateMsg.Deserialize(deserializer);
            deserializer.Read(out this.program_name);
            deserializer.Read(out this.answer);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.state);
            serializer.Write(this.program_name);
            serializer.Write(this.answer);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetProgramStateResponse: " +
            "\nstate: " + state.ToString() +
            "\nprogram_name: " + program_name.ToString() +
            "\nanswer: " + answer.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
