//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class GetSafetyModeResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/GetSafetyMode";
        public override string RosMessageName => k_RosMessageName;

        public SafetyModeMsg safety_mode;
        public string answer;
        public bool success;

        public GetSafetyModeResponse()
        {
            this.safety_mode = new SafetyModeMsg();
            this.answer = "";
            this.success = false;
        }

        public GetSafetyModeResponse(SafetyModeMsg safety_mode, string answer, bool success)
        {
            this.safety_mode = safety_mode;
            this.answer = answer;
            this.success = success;
        }

        public static GetSafetyModeResponse Deserialize(MessageDeserializer deserializer) => new GetSafetyModeResponse(deserializer);

        private GetSafetyModeResponse(MessageDeserializer deserializer)
        {
            this.safety_mode = SafetyModeMsg.Deserialize(deserializer);
            deserializer.Read(out this.answer);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.safety_mode);
            serializer.Write(this.answer);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "GetSafetyModeResponse: " +
            "\nsafety_mode: " + safety_mode.ToString() +
            "\nanswer: " + answer.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
