//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class IsProgramRunningResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/IsProgramRunning";
        public override string RosMessageName => k_RosMessageName;

        public string answer;
        public bool program_running;
        //  is a program running?
        public bool success;
        //  Did the dashboard server call succeed?

        public IsProgramRunningResponse()
        {
            this.answer = "";
            this.program_running = false;
            this.success = false;
        }

        public IsProgramRunningResponse(string answer, bool program_running, bool success)
        {
            this.answer = answer;
            this.program_running = program_running;
            this.success = success;
        }

        public static IsProgramRunningResponse Deserialize(MessageDeserializer deserializer) => new IsProgramRunningResponse(deserializer);

        private IsProgramRunningResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.answer);
            deserializer.Read(out this.program_running);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.answer);
            serializer.Write(this.program_running);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "IsProgramRunningResponse: " +
            "\nanswer: " + answer.ToString() +
            "\nprogram_running: " + program_running.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
