//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class IsProgramSavedResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/IsProgramSaved";
        public override string RosMessageName => k_RosMessageName;

        public string answer;
        public string program_name;
        public bool program_saved;
        //  is the current program saved?
        public bool success;
        //  Did the dashboard server call succeed?

        public IsProgramSavedResponse()
        {
            this.answer = "";
            this.program_name = "";
            this.program_saved = false;
            this.success = false;
        }

        public IsProgramSavedResponse(string answer, string program_name, bool program_saved, bool success)
        {
            this.answer = answer;
            this.program_name = program_name;
            this.program_saved = program_saved;
            this.success = success;
        }

        public static IsProgramSavedResponse Deserialize(MessageDeserializer deserializer) => new IsProgramSavedResponse(deserializer);

        private IsProgramSavedResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.answer);
            deserializer.Read(out this.program_name);
            deserializer.Read(out this.program_saved);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.answer);
            serializer.Write(this.program_name);
            serializer.Write(this.program_saved);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "IsProgramSavedResponse: " +
            "\nanswer: " + answer.ToString() +
            "\nprogram_name: " + program_name.ToString() +
            "\nprogram_saved: " + program_saved.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
