//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class LoadRequest : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/Load";
        public override string RosMessageName => k_RosMessageName;

        //  Service to load programs or installations
        public string filename;

        public LoadRequest()
        {
            this.filename = "";
        }

        public LoadRequest(string filename)
        {
            this.filename = filename;
        }

        public static LoadRequest Deserialize(MessageDeserializer deserializer) => new LoadRequest(deserializer);

        private LoadRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.filename);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.filename);
        }

        public override string ToString()
        {
            return "LoadRequest: " +
            "\nfilename: " + filename.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
