//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class PopupResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/Popup";
        public override string RosMessageName => k_RosMessageName;

        public string answer;
        public bool success;

        public PopupResponse()
        {
            this.answer = "";
            this.success = false;
        }

        public PopupResponse(string answer, bool success)
        {
            this.answer = answer;
            this.success = success;
        }

        public static PopupResponse Deserialize(MessageDeserializer deserializer) => new PopupResponse(deserializer);

        private PopupResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.answer);
            deserializer.Read(out this.success);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.answer);
            serializer.Write(this.success);
        }

        public override string ToString()
        {
            return "PopupResponse: " +
            "\nanswer: " + answer.ToString() +
            "\nsuccess: " + success.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
