//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class PopupRequest : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/Popup";
        public override string RosMessageName => k_RosMessageName;

        public string message;

        public PopupRequest()
        {
            this.message = "";
        }

        public PopupRequest(string message)
        {
            this.message = message;
        }

        public static PopupRequest Deserialize(MessageDeserializer deserializer) => new PopupRequest(deserializer);

        private PopupRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.message);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.message);
        }

        public override string ToString()
        {
            return "PopupRequest: " +
            "\nmessage: " + message.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
