//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class RawRequestResponse : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/RawRequest";
        public override string RosMessageName => k_RosMessageName;

        public string answer;

        public RawRequestResponse()
        {
            this.answer = "";
        }

        public RawRequestResponse(string answer)
        {
            this.answer = answer;
        }

        public static RawRequestResponse Deserialize(MessageDeserializer deserializer) => new RawRequestResponse(deserializer);

        private RawRequestResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.answer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.answer);
        }

        public override string ToString()
        {
            return "RawRequestResponse: " +
            "\nanswer: " + answer.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
