//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UrDashboard
{
    [Serializable]
    public class RawRequestRequest : Message
    {
        public const string k_RosMessageName = "ur_dashboard_msgs/RawRequest";
        public override string RosMessageName => k_RosMessageName;

        //  This service is there to support any dashboard query not explicitly supported
        public string query;

        public RawRequestRequest()
        {
            this.query = "";
        }

        public RawRequestRequest(string query)
        {
            this.query = query;
        }

        public static RawRequestRequest Deserialize(MessageDeserializer deserializer) => new RawRequestRequest(deserializer);

        private RawRequestRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.query);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.query);
        }

        public override string ToString()
        {
            return "RawRequestRequest: " +
            "\nquery: " + query.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
